language: rust
sudo: required
rust:
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
addons:
  apt:
    packages:
      - libssl-dev
      - libzmq3-dev
      - libpcre3-dev
      - libpq-dev
      - binutils-dev
