[package]
name = "rgb_node"
description = "RGB node"
version = "0.1.0-beta.1"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
license = "MIT"
keywords = ["bitcoin", "node", "layer-2", "smart-contracts", "rgb"]
edition = "2018"
readme = "README.md"

[lib]
name = "rgb"

[dependencies]
amplify = "~0.1.6"
amplify_derive = "~0.1.1"
base64 = "0.12"
dotenv = "~0.15.0"
clap = "=3.0.0-beta.1"
chrono = { version = "~0.4.11", features = [ "serde" ] }
serde = { version = "~1.0.111", features = ["derive"] }
serde_json = "~1.0.55"
serde_yaml = "~0.8.13"
toml = "~0.5.6"
bech32 = "~0.7.2"
log = { version = "~0.4", features = ["max_level_trace", "release_max_level_debug"] }
async-trait = "~0.1.35"
regex = "~1.3.9"
env_logger = "~0.7.1"
num-traits = "~0.2.12"
num-derive = "~0.3.0"
url = "~2.1.1"
diesel = { version = "~1.4.5", features = ["uuid", "numeric", "chrono"] } # target-specific features are coming, in the meantime keep postgres disabled to compile on android (https://github.com/rust-lang/cargo/issues/7914)
tokio = { version = "~0.2.21", features = ["full"] }
futures = "~0.3.5"
zmq = "~0.9.2"
tiny_http = "~0.7.0"
prometheus = "~0.9.0"
derive_wrapper = "~0.1.6"
# TODO: Move this dependency to LNP/BP core library
lightning-invoice = { git = "https://github.com/LNP-BP/rust-lightning-invoice.git", branch = "comment-systemtime-check" }

[dependencies.lnpbp]
git = "https://github.com/lnp-bp/rust-lnpbp"
branch = "master"
features = ["all"]

[dependencies.lnpbp_derive]
git = "https://github.com/lnp-bp/rust-lnpbp"
branch = "master"

[target.'cfg(target_os="android")'.dependencies.zmq]
version = "~0.9"
features = ["vendored"]

[features]
default = ["daemon", "fungibles", "collectibles", "identities"]
service = []
daemon = ["service"]
cli = []
fungibles = []
collectibles = []
identities = []

[workspace]
members = ["ffi"]

[patch.crates-io]
torut = { git = "https://github.com/afilini/torut", branch = "vendored-openssl-android" }
